server:
  port: 30001

management:
  server:
    port: 39001

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    health-check-url: http://${spring.cloud.client.ipaddress}:${management.server.port}/actuator/health
    metadata-map:
      management:
        port: ${management.server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.37.128:30001/eureka/,http://192.168.37.129:30001/eureka/