spring:
  application:
    name: servicenode-eureka-client
  banner:
    location: classpath:config/banner.txt
  profiles:
    active: local

info:
  name: '@porject.artifactId@'
  version: '@project.version@'
